config/routes.rb
Myapp::Application.routes.draw do
  get "posts/show"
  root :to => "home#index"
  devise_for :users
  resources :users
  get 'post/:url' => 'posts#show', :as => :post
  get 'disclaimer' => 'home#disclaimer', :as => :disclaimer

  resources :posts, :only => [:show] do
  	resources :comments, :only => [:create, :destroy, :update, :edit]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    unless user.nil?
      can :create, Comment
      can :manage, Comment, :user_id => user.id
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  before_save :clean_body

  belongs_to :user
  belongs_to :post
  
  attr_accessible :body

  validates_length_of :body, :allow_blank => false, :allow_nil => false, :maximum => 1000
  validate :raw_body_length

  private

  def raw_body_length
  	raw_body = Sanitize.clean(body, :elements => []).strip
  	if raw_body.nil? or raw_body.length < 1
  		errors.add(:body, "Не может быть пустым")
  	end
  end

  def clean_body
  	self.body = Sanitize.clean(body, :elements => ['p', 'i', 'b', 'strike'])
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	acts_as_url :title

	attr_accessible :announce, :body, :title

	def to_param
  		url
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = post.comments.build(params[:comment].permit(:body))
    authorize! :create, @comment
    @comment.user = current_user
    respond_to do |format|
      format.html {
        if @comment.save
          redirect_to(post, notice: "Комментарий добавлен")
        else
          render "posts/show"
        end
      }
      format.js {
        @comment.save
      }
    end
  end

  def edit
    @comment = post.comments.find(params[:id])
    authorize! :update, @comment
    respond_to do |format|
      format.js
    end
  end

  def update
    @comment = post.comments.find(params[:id])
    authorize! :update, @comment
    @comment.update_attributes(params[:comment])
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @comment = post.comments.find(params[:id])
    authorize! :delete, @comment
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to(post, notice: "Комментарий удален")}
      format.js
    end
  end

  private

  def post
    @post ||= Post.find_by_url(params[:post_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@posts = Post.all
  end

  def disclaimer
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
  	@post = Post.find_by_url!(params[:url])
  	@comment = Comment.new({:post_id => @post.id})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.row.comment{:id => "comment-#{comment.id}"}
  .large-12.columns
    - if comment.created_at
      = Russian::strftime(comment.created_at, "%d %B %H:%M")
    - unless comment.user.nil?
      = comment.user.email
    - else
      = "Анонимный комментарий"
    - if can? :delete, comment 
      = link_to "удалить", [@post, comment], :confirm => "Вы уверены?", :method => :delete, :remote => true
    - if can? :edit, comment
      = link_to "редактировать", edit_post_comment_path(@post, comment), :remote => true
    .comment-container{:id => "comment-container-#{comment.id}"}
      =raw comment.body

app/views/comments/_form.html.haml
- if @comment.errors.any?
  .row
    .large-12.columns
      -@comment.errors.full_messages.each do |msg|
        .alert-box
          = msg
          %a.close ×
= form_for [@post, @comment], :remote => true do |f|
  = f.text_area :body, :class => "redactor"
  - if @comment.id
    = submit_tag "Сохранить", :class => "button right", :style => "margin-top: 20px"
  - else
    = submit_tag "Добавить комментарий", :class => "button right", :style => "margin-top: 20px"
    

app/views/comments/_list.html.haml
#comments-list-container
- if @post.comments.count > 0
  = render :partial => 'comments/comment', :collection => @post.comments
- else
  %p{:id => "comments-not-found"}
    Комментарии к записи отсутствуют.

app/views/comments/create.js.erb
$('.comment:last').after('<%= escape_javascript(render(:partial =>  'comments/comment', locals: {comment: @comment})) %>');
$('#new_comment textarea').redactor('set', '');

app/views/comments/destroy.js.erb
$("#comment-<%=@comment.id%>").remove();

app/views/comments/edit.js.erb
$("#comment-container-<%=@comment.id%>").html('<%= escape_javascript(render(:partial =>  'comments/form')) %>');
start_redactor();

app/views/comments/update.js.erb
<% if @comment.errors.any? %>
	alert("Ошибка при добавлении комментария")
<% else %>
	$("#comment-<%=@comment.id%>").replaceWith('<%= escape_javascript(render(:partial =>  'comments/comment', locals: {comment: @comment})) %>');
<% end %>

app/views/home/disclaimer.html.haml
%h3 Добрый день

%p
  Тестовое задание немного расширил, добавив регистрацию и авторизацию.
  Так же для формы комментирования использовал redactor с небольшим количеством кнопок для стилизации. 
  Входной html фильтруется, так что другие теги не пройдут. Так же валидируется количество символов в тексте комментария (от 1 до 1000)

%p Авторизация на основе Devise, аутентификация на основе CanCan

%p Для постов используются нормальные ссылки, генерируемые при сохранении

%p Все работает с использованием TurboLinks

%p Верстка на основе Zurb Foundation, шаблоны haml

%p На текст поста в seed.rb лучше внимания не обращать, конечно же таким вещам там не место :)

app/views/home/index.html.haml
%h1 Посты
- @posts.each do |post|
  %h3
    = link_to post.title, post
  =raw post.announce
  = link_to "Продолжить чтение", post

app/views/layouts/_messages.html.haml
- unless flash.nil?
  .row
    .large-12.columns
      - flash.each do |name, msg|
        - if msg.is_a?(String)
          .alert-box
            = msg
            %a.close ×

app/views/layouts/_navigation.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %h1
        = link_to "Тестовое приложение", root_path

  %sextion.top-bar-section
    %ul.left
      %li.divider
      %li.active
        = link_to "Главная", root_path
      %li.divider
      %li
        = link_to "Дисклеймер", "/disclaimer"
      %li.divider
    %ul.right
      %li.divider
      - if user_signed_in?
        %li
          = link_to 'Выход', destroy_user_session_path, :method=>'delete'
      - else
        %li
          = link_to 'Вход', new_user_session_path
        %li.divider
        %li
          = link_to 'Регистрация', new_user_registration_path     

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Тестовое приложение"
      %meta{:content => content_for?(:description) ? yield(:description) : "Myapp", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    .row
      .large-12.columns
        = yield
    %footer
      %hr
      %p.text-center
        2013

app/views/posts/show.html.haml
= link_to "Вернуться на главную", root_path

%h2
  = link_to @post.title, @post
=raw @post.body

%h3 Комментарии

= render "comments/list"

- if user_signed_in?
  %hr
  %h5 Добавить новый комментарий
  = render 'comments/form'
- else
  %p
    Для того, чтобы написать комментарий, вам необходимо #{link_to "авторизоваться", new_user_session_path}